// THE TWO HAND-KEPT LISTS THAT BITE ON EVERY DEPLOY.
//
// 1. sw.js's PRECACHE module block. It was typed by hand, and on 2026-09-05 it
//    was missing FIVE modules the game actually imports — attacks, districts,
//    dressing, equipscene, ground — three of which every single level file
//    imports. That is not cosmetic. `install` only waits for CORE (the .js/
//    .html/.json entries), `activate` deletes every older cache, and the fetch
//    handler throws "offline and not cached" for anything absent. So a child
//    who opened the game right after an update, on a tablet with no signal,
//    could boot to the title and then fail to build any room at all.
//
// 2. The `#badge` version in index.html. CLAUDE.md says to bump it with
//    CACHE_NAME on every deploy, in bold, because letting them drift once cost
//    half an hour chasing a phantom cache bug (2026-08-29). A rule a human has
//    to remember on every deploy is a rule that gets forgotten; this is the
//    same rule, enforced.
//
// THE MODULE LIST IS COMPUTED FROM THE IMPORT GRAPH, not from `ls js/`. It
// walks static `from './x.js'` and dynamic `import('./x.js')` out from the
// entry in index.html. That is the difference between "every file in the
// folder" and "every file the game loads": js/skinify.js is in the folder,
// is imported by nothing, and correctly does NOT get precached. A dead file
// should not cost a child bandwidth on a phone.
//
//   node tools/sync-cache.mjs            check only; exit 1 if either drifted
//   node tools/sync-cache.mjs --write    rewrite both to match
//
// verify-boot.mjs runs the check, so this list can never rot again quietly.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve, relative } from 'node:path';

const ROOT = resolve(new URL('..', import.meta.url).pathname);
const SW = join(ROOT, 'sw.js');
const HTML = join(ROOT, 'index.html');
const WRITE = process.argv.includes('--write');

// --- 1. the import graph, from the entry index.html actually loads ----------
const html = readFileSync(HTML, 'utf8');
const entryMatch = html.match(/<script[^>]*type="module"[^>]*src="\.\/([^"]+)"/);
if (!entryMatch) throw new Error('index.html has no <script type="module" src="./...">');

// Both shapes, in one pass: `from './x.js'` / `from "./x.js"` and the dynamic
// `import('./x.js')`. Bare specifiers ("three") are import-map entries, not
// files in this repo, and are skipped — vendor/ is precached by hand.
const SPEC = /(?:from\s*|import\s*\(\s*)['"](\.[^'"]+\.js)['"]/g;

const seen = new Set();
const order = [];
const walk = (relPath) => {
  if (seen.has(relPath)) return;
  seen.add(relPath);
  order.push(relPath);
  const abs = join(ROOT, relPath);
  if (!existsSync(abs)) throw new Error(`imported but missing on disk: ${relPath}`);
  const src = readFileSync(abs, 'utf8');
  for (const m of src.matchAll(SPEC)) {
    const next = relative(ROOT, resolve(dirname(abs), m[1])).split('\\').join('/');
    walk(next);
  }
};
walk(entryMatch[1]);

// Entry first (it is the one that must be there), then alphabetical, so the
// generated block is stable and a diff shows only what really changed.
const entry = order[0];
const modules = [entry, ...order.slice(1).sort()];
const block = modules.map((m) => `  './${m}',`).join('\n');

// --- 2. splice it into sw.js between the sentinels --------------------------
const swSrc = readFileSync(SW, 'utf8');
const OPEN = '  // <<< generated by tools/sync-cache.mjs — do not edit by hand';
const CLOSE = '  // >>> end generated modules';
const region = new RegExp(`${OPEN.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${CLOSE.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`);
if (!region.test(swSrc)) throw new Error('sw.js is missing the generated-module sentinels');
const swWanted = swSrc.replace(region, `${OPEN}\n${block}\n${CLOSE}`);

// --- 3. the badge follows CACHE_NAME ---------------------------------------
const version = (swSrc.match(/CACHE_NAME\s*=\s*'wolfknight-(v[\d.]+)'/) || [])[1];
if (!version) throw new Error("sw.js has no CACHE_NAME of the form 'wolfknight-vX.Y.Z'");
const BADGE = /(<div id="badge">Wolf Knight &middot; )v[\d.]+(<\/div>)/;
if (!BADGE.test(html)) throw new Error('index.html has no #badge div in the expected shape');
const htmlWanted = html.replace(BADGE, `$1${version}$2`);

// --- 4. report or write -----------------------------------------------------
const swDrift = swWanted !== swSrc;
const badgeDrift = htmlWanted !== html;

if (swDrift) {
  const listed = new Set([...swSrc.matchAll(/'\.\/(js\/[^']+)'/g)].map((m) => m[1]));
  const missing = modules.filter((m) => !listed.has(m));
  const extra = [...listed].filter((m) => !modules.includes(m));
  if (missing.length) console.log('precache MISSING (imported but not cached):', missing.join(' '));
  if (extra.length) console.log('precache EXTRA (cached but never imported):', extra.join(' '));
  if (!missing.length && !extra.length) console.log('precache module block is out of order');
}
if (badgeDrift) {
  const was = html.match(/id="badge">Wolf Knight &middot; (v[\d.]+)</);
  console.log(`badge drift: index.html says ${was ? was[1] : '(unreadable)'}, sw.js CACHE_NAME says ${version}`);
}

if (!swDrift && !badgeDrift) {
  console.log(`ALL CLEAN — ${modules.length} modules precached, badge and CACHE_NAME both ${version}`);
  process.exit(0);
}
if (!WRITE) {
  console.log('\nrun: node tools/sync-cache.mjs --write');
  process.exit(1);
}
if (swDrift) writeFileSync(SW, swWanted);
if (badgeDrift) writeFileSync(HTML, htmlWanted);
console.log(`written — ${modules.length} modules precached, badge and CACHE_NAME both ${version}`);
